### TRAER TAREAS
GET http://localhost:3000/foros

### CREAR TAREA
POST http://localhost:3000/foros
Content-Type: application/json

{
  "title": "Problema de seguridad en formulario de inicio de sesión",
  "description": "Tengo preocupaciones sobre la seguridad en el formulario de inicio de sesión de mi sitio web. ¿Pueden ayudarme a identificar y solucionar posibles vulnerabilidades?",
  "poster_url": "https://ejemplo.com/imagen-problema10.jpg"
}



### MODIFICAR TAREA
PUT http://localhost:3000/3
Content-Type: application/json

{
    "title": "24"
}

### ELIMINAR
DELETE http://localhost:3000/2